/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabletest;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Merlin
 */
public class AddTable extends javax.swing.JFrame {
    
    
    String[] textFieldInputs;
    String[] textFieldDefaultText; //Enthält die Beschreibungen der Eingabefelder, um zu prüfen, ob der Inhalt beim ersten Mal bearbeiten geläscht werden soll.
    public AddTable() {
        this.textFieldDefaultText = new String[]{"EAN", "Artikelname","Artikelbeschreibung","VK Preis in EUR","Bestand"};
        this.textFieldInputs = new String[5];
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lHeadline = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        tfEAN = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfBeschreibung = new javax.swing.JTextField();
        tfVkPreis = new javax.swing.JTextField();
        tfBestand = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lHeadline.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lHeadline.setText("Artikel hinzufügen");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        tfEAN.setText("EAN");
        tfEAN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEANFocusGained(evt);
            }
        });

        tfName.setText("Artikelname");
        tfName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNameFocusGained(evt);
            }
        });

        tfBeschreibung.setText("Artikelbeschreibung");
        tfBeschreibung.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfBeschreibungFocusGained(evt);
            }
        });

        tfVkPreis.setText("VK Preis in EUR");
        tfVkPreis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfVkPreisFocusGained(evt);
            }
        });

        tfBestand.setText("Bestand");
        tfBestand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfBestandFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lHeadline)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfBeschreibung, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfVkPreis, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfBestand, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfEAN, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lHeadline)
                .addGap(18, 18, 18)
                .addComponent(tfEAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfBeschreibung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfVkPreis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfBestand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        textFieldInputs[0]=tfEAN.getText();
        textFieldInputs[1]=tfName.getText();
        textFieldInputs[2]=tfBeschreibung.getText();
        textFieldInputs[3]=tfVkPreis.getText();
        textFieldInputs[4]=tfBestand.getText();
        
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void tfEANFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEANFocusGained
        if(textFieldDefaultText[0].equals(tfEAN.getText())){
            tfEAN.setText("");
        }
    }//GEN-LAST:event_tfEANFocusGained

    private void tfNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNameFocusGained
        if(textFieldDefaultText[1].equals(tfName.getText())){
            tfName.setText("");
        }
    }//GEN-LAST:event_tfNameFocusGained

    private void tfBeschreibungFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBeschreibungFocusGained
        if(textFieldDefaultText[2].equals(tfBeschreibung.getText())){
            tfBeschreibung.setText("");
        }
    }//GEN-LAST:event_tfBeschreibungFocusGained

    private void tfVkPreisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfVkPreisFocusGained
        if(textFieldDefaultText[3].equals(tfVkPreis.getText())){
            tfVkPreis.setText("");
        }
    }//GEN-LAST:event_tfVkPreisFocusGained

    private void tfBestandFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBestandFocusGained
        if(textFieldDefaultText[4].equals(tfBestand.getText())){
            tfBestand.setText("");
        }
    }//GEN-LAST:event_tfBestandFocusGained

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lHeadline;
    private javax.swing.JTextField tfBeschreibung;
    private javax.swing.JTextField tfBestand;
    private javax.swing.JTextField tfEAN;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfVkPreis;
    // End of variables declaration//GEN-END:variables
}
