/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tabletest;

import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Merlin
 */
public class AddTable extends javax.swing.JFrame {
    
    boolean DataCorrect=false;
    boolean AddFinshed=false;
    String[] textFieldInputs;
    String[] textFieldDefaultText; //Enthält die Beschreibungen der Eingabefelder, um zu prüfen, ob der Inhalt beim ersten Mal bearbeiten geläscht werden soll.
    public AddTable() {
        this.textFieldDefaultText = new String[]{"EAN", "Artikelname","Artikelbeschreibung","VK Preis in EUR","Bestand"};
        this.textFieldInputs = new String[5];
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lHeadline = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        tfEAN = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfBeschreibung = new javax.swing.JTextField();
        tfVkPreis = new javax.swing.JTextField();
        tfBestand = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lHeadline.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lHeadline.setText("Artikel hinzufügen");
        getContentPane().add(lHeadline, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 266, -1, -1));

        tfEAN.setText("EAN");
        tfEAN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfEANFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfEANFocusLost(evt);
            }
        });
        getContentPane().add(tfEAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 500, -1));

        tfName.setText("Artikelname");
        tfName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNameFocusGained(evt);
            }
        });
        getContentPane().add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 500, -1));

        tfBeschreibung.setText("Artikelbeschreibung");
        tfBeschreibung.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfBeschreibungFocusGained(evt);
            }
        });
        getContentPane().add(tfBeschreibung, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, 500, -1));

        tfVkPreis.setText("VK Preis in EUR");
        tfVkPreis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfVkPreisFocusGained(evt);
            }
        });
        getContentPane().add(tfVkPreis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 500, -1));

        tfBestand.setText("Bestand");
        tfBestand.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfBestandFocusGained(evt);
            }
        });
        getContentPane().add(tfBestand, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, 500, -1));

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        getContentPane().add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 181, 143, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        
        textFieldInputs[0]=tfEAN.getText();
        textFieldInputs[1]=tfName.getText();
        textFieldInputs[2]=tfBeschreibung.getText();
        textFieldInputs[3]=tfVkPreis.getText();
        textFieldInputs[4]=tfBestand.getText();
        tfEAN.setText(textFieldDefaultText[0]);
        tfName.setText(textFieldDefaultText[1]);
        tfBeschreibung.setText(textFieldDefaultText[2]);
        tfVkPreis.setText(textFieldDefaultText[3]);
        tfBestand.setText((textFieldDefaultText[4]));
        AddFinshed=true;
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void tfEANFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEANFocusGained
        if(textFieldDefaultText[0].equals(tfEAN.getText())){
            tfEAN.setText("");
        }
    }//GEN-LAST:event_tfEANFocusGained

    private void tfNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNameFocusGained
        if(textFieldDefaultText[1].equals(tfName.getText())){
            tfName.setText("");
        }
    }//GEN-LAST:event_tfNameFocusGained

    private void tfBeschreibungFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBeschreibungFocusGained
        if(textFieldDefaultText[2].equals(tfBeschreibung.getText())){
            tfBeschreibung.setText("");
        }
    }//GEN-LAST:event_tfBeschreibungFocusGained

    private void tfVkPreisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfVkPreisFocusGained
        if(textFieldDefaultText[3].equals(tfVkPreis.getText())){
            tfVkPreis.setText("");
        }
    }//GEN-LAST:event_tfVkPreisFocusGained

    private void tfBestandFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfBestandFocusGained
        if(textFieldDefaultText[4].equals(tfBestand.getText())){
            tfBestand.setText("");
        }
    }//GEN-LAST:event_tfBestandFocusGained

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        
    }//GEN-LAST:event_formWindowLostFocus

    private void tfEANFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfEANFocusLost
        try {
            if(Integer.valueOf(tfEAN.getText())>0 
           && Integer.valueOf(tfEAN.getText())<100000)
            {
                DataCorrect=true;
                tfEAN.setBackground(Color.white);
            }
            else{
                tfEAN.setBackground(Color.red);
                DataCorrect=false;
        }
        } catch (Exception e) {
            tfEAN.setBackground(Color.red);
        }
        
    }//GEN-LAST:event_tfEANFocusLost

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel lHeadline;
    private javax.swing.JTextField tfBeschreibung;
    private javax.swing.JTextField tfBestand;
    private javax.swing.JTextField tfEAN;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfVkPreis;
    // End of variables declaration//GEN-END:variables
}
